# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XiMaLaYa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for XiMaLaYa
  pod 'Masonry'
  pod ‘Masonry’
  pod ‘AFNetworking’
  pod ‘MJExtension’
  pod ‘WMPageController’
  pod ‘MJRefresh’
  pod ‘BlocksKit’
  pod ‘MBProgressHUD’
end
